INSERT INTO author (firstname, lastname, version) VALUES ('Joshua', 'Bloch', 0);
INSERT INTO author (firstname, lastname, version) VALUES ('Gavin', 'King', 0);
INSERT INTO author (firstname, lastname, version) VALUES ('Christian', 'Bauer', 0);
INSERT INTO author (firstname, lastname, version) VALUES ('Gary', 'Gregory', 0);
INSERT INTO author (firstname, lastname, version) VALUES ('Raoul-Gabriel', 'Urma', 0);
INSERT INTO author (firstname, lastname, version) VALUES ('Mario', 'Fusco', 0);
INSERT INTO author (firstname, lastname, version) VALUES ('Alan', 'Mycroft', 0);
INSERT INTO author (firstname, lastname, version) VALUES ('Andrew Lee', 'Rubinger', 0);
INSERT INTO author (firstname, lastname, version) VALUES ('Aslak', 'Knutsen', 0);
INSERT INTO author (firstname, lastname, version) VALUES ('Bill', 'Burke', 0);
INSERT INTO author (firstname, lastname, version) VALUES ('Scott', 'Oaks', 0);